#!/usr/bin/env bash

# Shared defaults for setup, startup, validation, and the helper server.

export CODESPACES_VLESS_WORKSPACE="${CODESPACES_VLESS_WORKSPACE:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
export CODESPACES_VLESS_ROOT="${CODESPACES_VLESS_ROOT:-${CODESPACES_VLESS_WORKSPACE}/.local/codespaces-vless}"

export CODESPACES_VLESS_BIN_DIR="${CODESPACES_VLESS_BIN_DIR:-${CODESPACES_VLESS_ROOT}/bin}"
export CODESPACES_VLESS_CONFIG_DIR="${CODESPACES_VLESS_CONFIG_DIR:-${CODESPACES_VLESS_ROOT}/config}"
export CODESPACES_VLESS_STATE_DIR="${CODESPACES_VLESS_STATE_DIR:-${CODESPACES_VLESS_ROOT}/state}"
export CODESPACES_VLESS_LOG_DIR="${CODESPACES_VLESS_LOG_DIR:-${CODESPACES_VLESS_ROOT}/logs}"
export CODESPACES_VLESS_RUN_DIR="${CODESPACES_VLESS_RUN_DIR:-${CODESPACES_VLESS_ROOT}/run}"
export CODESPACES_VLESS_DOWNLOAD_DIR="${CODESPACES_VLESS_DOWNLOAD_DIR:-${CODESPACES_VLESS_ROOT}/downloads}"

export CODESPACES_VLESS_PORT="${CODESPACES_VLESS_PORT:-10086}"
export CODESPACES_VLESS_HELPER_PORT="${CODESPACES_VLESS_HELPER_PORT:-18080}"
export CODESPACES_VLESS_NODE_NAME="${CODESPACES_VLESS_NODE_NAME:-codespace-vless}"
export CODESPACES_VLESS_WS_PATH="${CODESPACES_VLESS_WS_PATH:-/vless}"
export CODESPACES_VLESS_XRAY_VERSION="${CODESPACES_VLESS_XRAY_VERSION:-v26.3.27}"

export CODESPACES_VLESS_XRAY_BIN="${CODESPACES_VLESS_XRAY_BIN:-${CODESPACES_VLESS_BIN_DIR}/xray}"
export CODESPACES_VLESS_UUID_FILE="${CODESPACES_VLESS_UUID_FILE:-${CODESPACES_VLESS_STATE_DIR}/vless.uuid}"
export CODESPACES_VLESS_XRAY_CONFIG="${CODESPACES_VLESS_XRAY_CONFIG:-${CODESPACES_VLESS_CONFIG_DIR}/xray-server.json}"
export CODESPACES_VLESS_XRAY_PID="${CODESPACES_VLESS_XRAY_PID:-${CODESPACES_VLESS_RUN_DIR}/xray.pid}"
export CODESPACES_VLESS_HELPER_PID="${CODESPACES_VLESS_HELPER_PID:-${CODESPACES_VLESS_RUN_DIR}/helper.pid}"
export CODESPACES_VLESS_XRAY_LOG="${CODESPACES_VLESS_XRAY_LOG:-${CODESPACES_VLESS_LOG_DIR}/xray.log}"
export CODESPACES_VLESS_HELPER_LOG="${CODESPACES_VLESS_HELPER_LOG:-${CODESPACES_VLESS_LOG_DIR}/helper.log}"
export CODESPACES_VLESS_STARTUP_LOG="${CODESPACES_VLESS_STARTUP_LOG:-${CODESPACES_VLESS_LOG_DIR}/startup.log}"

codespaces_vless_ensure_dirs() {
  mkdir -p \
    "${CODESPACES_VLESS_BIN_DIR}" \
    "${CODESPACES_VLESS_CONFIG_DIR}" \
    "${CODESPACES_VLESS_STATE_DIR}" \
    "${CODESPACES_VLESS_LOG_DIR}" \
    "${CODESPACES_VLESS_RUN_DIR}" \
    "${CODESPACES_VLESS_DOWNLOAD_DIR}"
}
